packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true

catalog:
  "@types/node": ^24
  astro: ^6.1.2
  emdash: ^0.1.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plus: latest

catalogMode: prefer
overrides:
  typescript: "catalog:"
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
