// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from 'emdash'

export interface Friend {
  id: string
  slug: string | null
  status: string
  website: string
  description?: string
  homepage: string
  poster: string
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  bylines?: ContentBylineCredit[]
}

export interface Page {
  id: string
  slug: string | null
  status: string
  title: string
  date: string
  updated?: string
  comments?: boolean
  cover: string
  og?: string
  published?: boolean
  summary?: string
  toc?: boolean
  content?: PortableTextBlock[]
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  bylines?: ContentBylineCredit[]
}

export interface Post {
  id: string
  slug: string | null
  status: string
  title: string
  date: string
  updated?: string
  comments?: boolean
  alias?: unknown
  summary?: string
  cover?: string
  og?: string
  published?: boolean
  visible?: boolean
  toc?: boolean
  content?: PortableTextBlock[]
  createdAt: Date
  updatedAt: Date
  publishedAt: Date | null
  bylines?: ContentBylineCredit[]
}

declare module 'emdash' {
  interface EmDashCollections {
    friends: Friend
    pages: Page
    posts: Post
  }
}
